#!/usr/bin/env ruby
require 'pathname'

TYPES = %w(container component)

type = ARGV.shift
name = ARGV.shift

raise 'Invalid type' unless type && TYPES.include?(type)
raise 'Invalid name' unless name

javascript = <<-JS
import React, { Component } from 'react'

import css from './styles.scss'

export default class #{name} extends Component {
  render() {
    return (

    )
  }
}
JS

path = Pathname.new(File.expand_path(File.dirname(__FILE__))).join('src', "#{type}s", name)

Dir.mkdir(path)

File.open(path.join('index.js'), 'w+') { |f| f.write(javascript.strip) }
File.open(path.join('styles.scss'), 'w+') { |f| f.close }
